# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: downloadertask@1
  inputs:
    connectionId: 'CWCC.BMC.COM:16196#1047 - Latin 1 (Open Systems)'
    runtimeConfig: 'iccga'
    ispwUserId: 'pfhmks0'
    password: '$(ispwPassword)'
    windowsTopazWorkbenchCliHome: 'C:\TWB-20.13.01\CLI'
    sourceDownloadLocation: 'c:\ADOData'
    downloadSourceType: 'Container'
    containerType: 'Assignment'
    containerId: 'MKS1000361'
- task: azure-deveops-ispw-operation-task@2
  inputs:
    connectionId: 'CWCC.BMC.COM:16196#1047 - Latin 1 (Open Systems)'
    operationType: 'CES'
    cesUrl: 'http://aus-bdc-cwcc.bmc.com:2020/'
    cesSecretToken: '$(cesToken)'
    action: 'GenerateTasksInAssignment'
    request: |
      assignmentId=MKS1000361
      level=DEV3
    skipWaitingForSetCompletion: false
    showResponseBodyInConsole: true